name: Build and Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
jobs:
  mac-build:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"
      - name: Build macOS ARM64 Binary
        run: swift build -c release --arch arm64
      - name: Build macOS Intel Binary
        run: swift build -c release --arch x86_64
      # - name: Run tests
      #   run: swift test -v
      - name: Merge Binaries into Universal
        run: lipo -create -output "strumvg" ".build/arm64-apple-macosx/release/strumvg" ".build/x86_64-apple-macosx/release/strumvg"
      - name: Set Permissions on Binary to Allow Run
        run: chmod 755 strumvg
      - name: Remove Quarantine Attribute from Binary
        run: xattr -d com.apple.quarantine strumvg
      - name: Rename Binary
        run: mv "strumvg" "strumvg-macos"
      - name: 'Upload macOS Build Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: strumvg-macos
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - mac-build
    steps:
      - name: Download Artifacts from Previous Jobs
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: List downloaded files
        run: ls -R
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          files: './*/*'
          fail_on_unmatched_files: true
