# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build and Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - '*.*.*'
jobs:
  mac-build:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"
      - name: Build macOS Binary
        run: swift build -v -c release --arch x86_64 --arch arm64
      # - name: Run tests
      #   run: swift test -v
      - name: "Move/Rename Binary"
        run: cp ".build/release/strumvg" "builds/strumvg-macos"
      - name: 'Upload macOS Build Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: strumvg-macos
          path: builds/strumvg-macos
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - mac-build
    steps:
      - name: Download Artifacts from Previous Jobs
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: List downloaded files
        run: ls -R
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          files: ./builds/
          fail_on_unmatched_files: true
